[package]
name = "dvd_categorizer_web"
version = "0.1.0"
authors = ["1x2kb <natemeyer@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = ["router"] }
# log.workspace = true
# pretty_env_logger.workspace = true
# tracing.workspace = true
dotenvy.workspace = true
models = { path = "../models", features = [] }

[patch.crates-io]
getrandom = { version = "0.2.15", features = ["js"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
