// Generated by diesel_ext
// TODO: Move to models crate
#![allow(unused)]
#![allow(clippy::all)]

use std::fmt::{format, Display};

use crate::schema::*;
#[cfg(feature = "testing")]
use crate::Random;

use diesel::prelude::*;
use movie_genre::genre;
#[cfg(feature = "testing")]
use rand::{thread_rng, Rng};
use serde::{Deserialize, Serialize};

#[derive(
    Queryable, Selectable, Debug, Clone, Identifiable, PartialEq, Eq, Serialize, Deserialize,
)]
#[diesel(table_name = actor)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Actor {
    pub id: i32,
    pub name: String,
}

impl From<String> for Actor {
    fn from(value: String) -> Self {
        Self { id: 0, name: value }
    }
}

impl
    From<(
        i32,
        String,
    )> for Actor
{
    fn from(
        (id, name): (
            i32,
            String,
        ),
    ) -> Self {
        Self { id, name }
    }
}

#[derive(Debug, Clone, Insertable)]
#[diesel(table_name = actor)]
#[diesel(check_for_backend(diesel::pg::PG))]
pub struct NewActor {
    pub name: String,
}

#[derive(
    Queryable, Debug, Insertable, Clone, Identifiable, PartialEq, Eq, Serialize, Deserialize,
)]
#[diesel(table_name = director)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Director {
    pub id: i32,
    pub name: String,
}

#[derive(Insertable)]
#[diesel(table_name = director)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewDirector {
    pub name: String,
}

impl From<String> for Director {
    fn from(name: String) -> Self {
        Self { id: 0, name }
    }
}

#[derive(Queryable, Debug, Insertable, Identifiable)]
#[diesel(table_name = movie)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Movie {
    pub id: i32,
    pub name: String,
    pub director_id: Option<i32>,
    pub description: Option<String>,
}

#[derive(Insertable, Debug, Clone)]
#[diesel(table_name = movie)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewMovie {
    pub name: String,
    pub director_id: Option<i32>,
    pub description: Option<String>,
}

#[derive(Queryable, Debug, Insertable, Associations, Identifiable)]
#[diesel(table_name = movie_actor)]
#[diesel(belongs_to(Movie))]
#[diesel(belongs_to(Actor))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct MovieActor {
    pub id: i32,
    pub movie_id: i32,
    pub actor_id: i32,
}

#[derive(Insertable)]
#[diesel(table_name = movie_actor)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewMovieActor {
    pub movie_id: i32,
    pub actor_id: i32,
}

#[derive(Queryable, Debug, Associations, Identifiable)]
#[diesel(table_name = movie_genre)]
#[diesel(belongs_to(Movie))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct MovieGenre {
    pub id: i32,
    pub movie_id: i32,
    pub genre: String,
}

#[derive(Debug, Insertable, Clone)]
#[diesel(table_name = movie_genre)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct NewMovieGenre {
    pub movie_id: i32,
    pub genre: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FullMovie {
    pub id: i32,
    pub name: String,
    pub description: Option<String>,

    pub actors: Vec<Actor>,
    pub director: Option<Director>,
    pub genres: Vec<String>,
}

impl
    From<(
        Movie,
        Option<Director>,
        Vec<Actor>,
        Vec<String>,
    )> for FullMovie
{
    fn from(
        (movie, director, actors, genres): (
            Movie,
            Option<Director>,
            Vec<Actor>,
            Vec<String>,
        ),
    ) -> Self {
        Self {
            id: movie.id,
            name: movie.name,
            description: movie.description,
            director,
            actors,
            genres,
        }
    }
}

#[cfg(feature = "testing")]
impl Random for Actor {
    fn random() -> Self {
        let id = thread_rng().gen_range(0..100000000);

        Self {
            id,
            name: format!(
                "Actor Name {}",
                thread_rng().gen_range(0..1000)
            ),
        }
    }
}
#[cfg(feature = "testing")]
impl Random for Director {
    fn random() -> Self {
        Self {
            id: rand::thread_rng().gen_range(0..10000000),
            name: format!(
                "Director Name {}",
                thread_rng().gen_range(0..1000)
            ),
        }
    }
}

#[cfg(feature = "testing")]
const GENRES: [&'static str; 4] = ["Western", "Action", "Sci-Fi", "Fantasy"];

#[cfg(feature = "testing")]
impl Random for FullMovie {
    fn random() -> Self {
        let mut random = thread_rng();
        let num_actors = random.gen_range(1..10);
        let num_genres = random.gen_range(1..4);

        Self {
            id: random.gen_range(0..10000000),
            name: format!(
                "Movie Title {}",
                random.gen_range(0..1000),
            ),
            description: Some(
                format!(
                    "Movie Description {}",
                    random.gen_range(0..1000),
                ),
            ),
            actors: (0..num_actors)
                .map(|_| Actor::random())
                .collect(),
            director: Some(Director::random()),
            genres: (1..num_genres)
                .map(|_| GENRES[random.gen_range(1..GENRES.len())].to_string())
                .collect(),
        }
    }
}
