[package]
name = "csv_utils"
version = "0.1.0"
edition = "2024"

[features]
postgres = ["models/postgres"]
vector-similarity = ["models/vector-similarity"]
default = ["postgres", "vector-similarity"]

[dependencies]
csv = "*"
models = { path = "../models" }
serde = { version = "1.0.214", features = ["derive"] }