[package]
name = "csv_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "*"
database = { path = "../database" }
serde = { version = "1.0.214", features = ["derive"] }
tokio.workspace = true
dotenvy.workspace = true
models = { path = "../models" }
log.workspace = true
env_logger.workspace = true
tracing.workspace = true
ai_chat = { path = "../ai_chat" }
csv_utils = { path = "../csv_utils" }
